services:
  fcp-fd-data:
    build:
      context: .
      target: production
    image: fcp-fd-data
    container_name: fcp-fd-data
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-data-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
