services:
  fcp-fd-data:
    build:
      context: .
      target: production
    image: fcp-fd-data
    container_name: fcp-fd-data
    depends_on: 
      - fcp-fd-data-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-data-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      POSTGRES_DB: fcp_fd_data
      POSTGRES_HOST: ${POSTGRES_HOST:-fcp-fd-data-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      DATA_TOPIC_ADDRESS: ${DATA_TOPIC_ADDRESS:-fcp-fd-data}${MESSAGE_QUEUE_SUFFIX}
      DATA_SUBSCRIPTION_ADDRESS: ${DATA_SUBSCRIPTION_ADDRESS:-fcp-fd-data}${MESSAGE_QUEUE_SUFFIX}
      ENVIRONMENT_CODE: ${ENVIRONMENT_CODE:-dev}
  
  fcp-fd-data-postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: fcp_fd_data
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
