{{- include "ffc-helm-library.container-config-map" (list . "fcp-fd-data.config-map") -}}
{{- define "fcp-fd-data.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  MESSAGE_QUEUE_HOST: {{ .Values.container.messageQueueHost | quote }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  COMMS_TOPIC_ADDRESS: {{ .Values.container.commsTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  COMMS_TOPIC_ADDRESS: {{ .Values.container.commsTopicAddress | quote }}
  {{- end }}
  COMMS_SUBSCRIPTION_ADDRESS: {{ .Values.container.commsSubscriptionAddress }}
  ENVIRONMENT_CODE: {{ quote .Values.environmentCode }}
{{- end -}}
