environment: production
environmentCode:
name: fcp-fd-data
namespace: fcp-fd
workstream: fcp-fd
image: fcp-fd-data

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: fcp-fd-data-config-map

containerSecret:
  name: fcp-fd-data-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3004

livenessProbe:
  path: /healthz
  port: 3004
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3004
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

postgresService:
  postgresDb: fcp_fd_data
  postgresExternalName:
  postgresHost: fcp-fd-data-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

usePodIdentity: true

azureIdentity:
  resourceID: not-a-real-clientID
  clientID: not-a-real-clientID
