environment: production
environmentCode:
name: fcp-fd-data
namespace: fcp-fd
workstream: fcp-fd
image: fcp-fd-data

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: fcp-fd-data-config-map

containerSecret:
  name: fcp-fd-data-container-secret
  type: Opaque

deployment: {}

port: &port 3033

container:
  resourceTier: M
  port: *port
  messageQueueHost: namespace.servicebus.windows.net
  dataSubscriptionAddress: fcp-fd-data
  dataTopicAddress: fcp-fd-data

livenessProbe:
  path: /healthz
  port: *port
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: *port
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

postgresService:
  postgresDb: fcp_fd_data
  postgresExternalName:
  postgresqlHost: fcp-fd-data-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

usePodIdentity: true

azureIdentity:
  resourceID: not-a-real-clientID
  clientID: not-a-real-clientID

ingress:
  class: nginx
  endpoint: fcp-fd-data
  server: